const { getPool } = require("../lib/browser-pool");
const { resolveFormatOptions } = require("../lib/config");

var PAGE_SIZES = {
  A3: "297mm 420mm",
  A4: "210mm 297mm",
  A5: "148mm 210mm",
  Legal: "8.5in 14in",
  Letter: "8.5in 11in",
  Tabloid: "11in 17in",
};

/* Print CSS that preserves all styling (shadows, backgrounds, colors).
 * The @page rule is built to match the requested format/landscape/margin so
 * that page.pdf({ format, landscape, margin }) stays consistent with the CSS
 * page size (preferCSSPageSize: true would otherwise let a hardcoded A4 rule
 * silently override the caller's format choice). */
function buildPrintCss(format, landscape, margin) {
  var size = PAGE_SIZES[format] || PAGE_SIZES.A4;
  if (landscape) {
    var dims = size.split(" ");
    size = dims[1] + " " + dims[0];
  }
  return `
@page {
  size: ${size};
  margin: ${margin};
}
@media print {
  body {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
    color-adjust: exact !important;
  }
  img {
    max-width: 100% !important;
    height: auto !important;
    page-break-inside: avoid;
  }
  table, pre, blockquote, figure, .card, .keep-together {
    page-break-inside: avoid !important;
    break-inside: avoid !important;
  }
  h1, h2, h3, h4, h5, h6 {
    page-break-after: avoid !important;
    break-after: avoid !important;
  }
  p {
    orphans: 3;
    widows: 3;
  }
}
`;
}

function injectPrintCss(html, format, landscape, margin) {
  var styleTag = '<style>' + buildPrintCss(format, landscape, margin) + '</style>';
  if (html.indexOf("</head>") >= 0) {
    return html.replace("</head>", styleTag + "</head>");
  }
  return '<!DOCTYPE html><html><head>' + styleTag + '</head><body>' + html + '</body></html>';
}

async function convertToPdf(html, options) {
  var cfg = resolveFormatOptions("pdf", options);
  var {
    width = cfg.width,
    height = cfg.height,
    scale = cfg.scale,
    format = cfg.pdf.format,
    landscape = cfg.pdf.landscape,
    printBackground = cfg.pdf.printBackground,
    headerFooter = cfg.pdf.headerFooter,
    margin = cfg.pdf.margin,
  } = options || {};

  var pool = getPool();

  return pool.execute(async (page) => {
    await page.setViewport({ width, height, deviceScaleFactor: scale });

    var modifiedHtml = injectPrintCss(html, format, landscape, margin);
    await page.setContent(modifiedHtml, { waitUntil: "networkidle2", timeout: 30000 });

    await page.evaluate(() => document.fonts && document.fonts.ready);
    await new Promise((r) => setTimeout(r, 800));

    var pageDimensions = await page.evaluate(() => ({
      scrollW: document.documentElement.scrollWidth,
      scrollH: document.documentElement.scrollHeight,
      bodyW: document.body.scrollWidth,
      bodyH: document.body.scrollHeight,
    }));

    var pdfOptions = {
      format: format,
      landscape: landscape,
      printBackground: printBackground,
      margin: {
        top: margin,
        right: margin,
        bottom: margin,
        left: margin,
      },
      preferCSSPageSize: true,
    };

    if (headerFooter) {
      pdfOptions.displayHeaderFooter = true;
      pdfOptions.headerTemplate = `
        <div style="width:100%;padding:0 ${margin};font-size:8px;color:#9ca3af;display:flex;justify-content:space-between;font-family:Arial,sans-serif;">
          <span>HTML Export</span>
          <span class="date"></span>
        </div>
      `;
      pdfOptions.footerTemplate = `
        <div style="width:100%;padding:0 ${margin};font-size:8px;color:#9ca3af;display:flex;justify-content:space-between;font-family:Arial,sans-serif;">
          <span>Generated by HTML to Design</span>
          <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        </div>
      `;
    }

    return page.pdf(pdfOptions);
  }, { timeout: 120000, retries: 2 });
}

module.exports = { convertToPdf };
