const { getPool } = require("../lib/browser-pool");

const PRINT_CSS = `
@page {
  size: A4;
  margin: 15mm;
}
@media print {
  body {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
    color-adjust: exact !important;
  }
  img {
    max-width: 100% !important;
    height: auto !important;
    page-break-inside: avoid;
  }
  table, pre, blockquote, figure, .card, .keep-together {
    page-break-inside: avoid !important;
    break-inside: avoid !important;
  }
  h1, h2, h3, h4, h5, h6 {
    page-break-after: avoid !important;
    break-after: avoid !important;
  }
  p {
    orphans: 3;
    widows: 3;
  }
  .no-print, nav, .sidebar {
    display: none !important;
  }
  * {
    box-shadow: none !important;
    text-shadow: none !important;
  }
}
`;

async function convertToPdf(html, options) {
  const {
    width = 1440,
    height = 900,
    scale = 2,
    format = "A4",
    landscape = false,
    printBackground = true,
    headerFooter = true,
    margin = "15mm",
  } = options;

  const pool = getPool();

  return pool.execute(async (page) => {
    await page.setViewport({ width, height, deviceScaleFactor: 1 });

    let modifiedHtml = html;
    if (!html.includes("<style")) {
      modifiedHtml = html.replace("</head>", `<style>${PRINT_CSS}</style></head>`);
    } else {
      modifiedHtml = html.replace("</head>", `<style>${PRINT_CSS}</style></head>`);
    }

    await page.setContent(modifiedHtml, { waitUntil: "networkidle2", timeout: 30000 });
    await page.evaluate(() => document.fonts && document.fonts.ready);
    await new Promise((r) => setTimeout(r, 500));

    const pdfOptions = {
      format: format,
      landscape: landscape,
      printBackground: printBackground,
      margin: {
        top: margin,
        right: margin,
        bottom: margin,
        left: margin,
      },
    };

    if (headerFooter) {
      pdfOptions.displayHeaderFooter = true;
      pdfOptions.headerTemplate = `
        <div style="width:100%;padding:0 ${margin};font-size:9px;color:#9ca3af;display:flex;justify-content:space-between;font-family:Arial,sans-serif;">
          <span>HTML to Design Export</span>
          <span class="date"></span>
        </div>
      `;
      pdfOptions.footerTemplate = `
        <div style="width:100%;padding:0 ${margin};font-size:9px;color:#9ca3af;display:flex;justify-content:space-between;font-family:Arial,sans-serif;">
          <span>Generated by HTML to Design</span>
          <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        </div>
      `;
    }

    return page.pdf(pdfOptions);
  }, { timeout: 120000, retries: 2 });
}

module.exports = { convertToPdf };
