const { getPool } = require("../lib/browser-pool");

async function convertToSvg(html, options) {
  var { width = 1440, height = 900, scale = 2 } = options;
  var pool = getPool();

  return pool.execute(async (page) => {
    await page.setViewport({ width, height, deviceScaleFactor: scale });
    await page.setContent(html, { waitUntil: "networkidle2", timeout: 30000 });
    await page.evaluate(() => document.fonts && document.fonts.ready);
    await new Promise((r) => setTimeout(r, 500));

    await page.evaluate(() => {
      return new Promise((resolve) => {
        const images = document.querySelectorAll("img");
        let loaded = 0;
        const total = images.length;
        if (total === 0) return resolve();
        images.forEach((img) => {
          if (img.complete) {
            loaded++;
            if (loaded === total) resolve();
          } else {
            img.onload = () => { loaded++; if (loaded === total) resolve(); };
            img.onerror = () => { loaded++; if (loaded === total) resolve(); };
          }
        });
        setTimeout(resolve, 3000);
      });
    });

    var pngBuffer = await page.screenshot({ type: "png", fullPage: true });

    var dimensions = await page.evaluate(() => ({
      width: document.documentElement.scrollWidth,
      height: document.documentElement.scrollHeight,
    }));

    var svgContent = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
     width="${dimensions.width}" height="${dimensions.height}"
     viewBox="0 0 ${dimensions.width} ${dimensions.height}">
  <title>HTML Export</title>
  <desc>Generated by HTML to Design converter</desc>
  <defs>
    <style type="text/css"><![CDATA[
      text { font-family: Inter, system-ui, -apple-system, sans-serif; }
    ]]></style>
  </defs>
  <rect width="100%" height="100%" fill="#ffffff"/>
  <image width="${dimensions.width}" height="${dimensions.height}"
         xlink:href="data:image/png;base64,${pngBuffer.toString("base64")}" />
</svg>`;

    return Buffer.from(svgContent, "utf-8");
  }, { timeout: 60000, retries: 3 });
}

module.exports = { convertToSvg };
